# .makim.yaml
# ----------------------------------------------------------------------
# Tasks for the shell scripts in the ./scripts directory
# ----------------------------------------------------------------------

groups:
  scripts:
    tasks:
      build:
        help: Build project artifacts
        backend: bash
        run: ./scripts/build.sh

      test:
        help: Run unit/integration tests
        backend: bash
        run: ./scripts/test.sh

      run:
        help: Launch the application locally
        backend: bash
        run: ./scripts/run.sh

      deploy:
        help: Deploy the application to the target environment
        backend: bash
        run: ./scripts/deploy.sh

      cleanup:
        help: Remove temporary files, containers, and other build artifacts
        backend: bash
        run: ./scripts/cleanup.sh

      check_plugin_service:
        help: Health-check the plugin service
        backend: bash
        run: ./scripts/check_plugin_service.sh

      demo_rotation:
        help: Run demo rotation scenario
        backend: bash
        run: ./scripts/demo-rotation.sh

  ci:
    # Aggregate tasks useful for CI pipelines
    tasks:
      all:
        help: Run the same steps that CI executes
        hooks:
          pre-run:
            - task: scripts.build
            - task: scripts.test
            - task: scripts.check_plugin_service
            - task: scripts.cleanup
